version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
      - "6006:6006"
      - "5173:5173"
    volumes:
      - ./app:/var/www/html/app
    # environment:
    environment:
      - APACHE_SERVER_NAME=localhost
      - CHOKIDAR_USEPOLLING=true
    command: sh -c ' npm i --legacy-peer-deps && npm run dev'
